### ISSUE TITLE
Conversion issue - 1 minute

### ISSUE THREAD

**Issue by SirMotte** [Ethaks/FVTT-Metron#1]
Thank you for this wonderful tool. I've been using a similar one up until now, but yours is lightning fast.  Awesome!

While testing I stumbled across the issue below. 1 minute is converted to 1.5 km(nute) which obviously is undesirable.
![grafik](https://user-images.githubusercontent.com/82598692/213519497-b013736a-92c7-4604-a014-fe8e99169a6d.png)

Thanks!

**Comment by Ethaks** [comment]
Welp, that conversion is of course quite nonsensical. Above commit should prevent that from happening.
