### ISSUE TITLE
Conversion not included - gallons, (ounces?) and cubic feet, inch

### ISSUE THREAD

**Issue by SirMotte** [Ethaks/FVTT-Metron#2]
The following conversion metrics seem to be missing, same might be true for ounces (not tested yet)

![grafik](https://user-images.githubusercontent.com/82598692/213520742-f81015c9-69ae-42bf-a0d3-88a0faa16441.png)

Also, this instance of inch seems not to be converted properly.
![grafik](https://user-images.githubusercontent.com/82598692/213521417-e957c59f-15d6-41f8-bcbb-ed5ba33808dc.png)

**Comment by Ethaks** [comment]
Converted units are currently limited to those covered by WotC shenanigans, as this module was written specifically for the introduction of simplified rates for feet → metres, miles → kilometres, and lbs → kg.

I haven't decided yet whether fully covering everything there is should be part of the module's scope. While individual additions are not too terrible, the full breadth of units and conversion rates makes full coverage quite the project.

**Comment by SirMotte** [comment]
> Converted units are currently limited to those covered by WotC shenanigans, as this module was written specifically for the introduction of simplified rates for feet → metres, miles → kilometres, and lbs → kg.
> 
> I haven't decided yet whether fully covering everything there is should be part of the module's scope. While individual additions are not too terrible, the full breadth of units and conversion rates makes full coverage quite the project.

Understood. I'll use other means to translate those values then. Thanks for the fast response!

Maybe this module can help you with some of the values if you decide to add support at some point.
https://github.com/HadaIonut/Foundry-mgl
