### ISSUE TITLE
Conversion Issue - Kilometers

### ISSUE THREAD

**Issue by SirMotte** [Ethaks/FVTT-Metron#3]
Found another issue with scrambled text. This time with kilometers. Possibly because there is the spelling kilometer and kilometre?

![grafik](https://user-images.githubusercontent.com/82598692/213589943-80f3ee1b-740c-426e-b23c-914d18b7066f.png)

**Comment by Ethaks** [comment]
Did the module happen to mangle that description in an earlier version?
From quickly adding that sentence to the automated test cases, converting from imperial to metric and the other way (even repeatedly) seems to be fine.

**Comment by SirMotte** [comment]
> Did the module happen to mangle that description in an earlier version? From quickly adding that sentence to the automated test cases, converting from imperial to metric and the other way (even repeatedly) seems to be fine.

Whoops I just noticed that the module didn't update just now. Sorry, seems to be fixed alright!
