### ISSUE TITLE
TypeError: undefined. Cannot set properties of undefined (setting 'senses')

### ISSUE THREAD

**Issue by aronmero** [Ethaks/FVTT-Metron#6]
I get this error on some npc tokens when trying to convert them.  I added in src/module/documents/actor.mjs line 65 the following modification **updateData.system.attributes = updateData.system.attributes || {};** 
```js
if (!actor.items.some((i) => i.type === "race")) {
		updateData.system.attributes = updateData.system.attributes || {};
		for (const field of ["senses", "movement"]) {
			const fieldData = actor.system?.attributes?.[field];
			updateData.system.attributes[field] = convertDistanceField(fieldData, target);
		}
	}
```

I tried to make a pull request but it won't let me, I leave this issue created in case you see fit to add that fix.

**Comment by Ethaks** [comment]
Thanks for catching that error! I added the check in e4da253c25cb26a919f6fc346dea6bf470f3939b.
